### ISSUE TITLE
Failure in results reproduction

### ISSUE THREAD

**Issue by EB79** [AliRafiee7/SeConvNet#1]
Hi, Ali 
hope you be great,
I wanted to inform you about a problem which occurred after testing your code with model weights provided. I successfully run the code and model but I found images corrupted in results folder.
Could you tell us what is the wrong with our procedure?

My system resources :
intel xeon w5
256 GB RAM
48 GB NVIDIA A 6000
and all of your mentioned requirements have been satisfied.

![Baboon](https://github.com/AliRafiee7/SeConvNet/assets/59480858/64219081-1c8c-4bc1-8912-d14cf8d9a066)

**Comment by AliRafiee7** [comment]
Hi, I am not sure about how you tested our model, but you can also check and use our model using the Code Ocean platform on https://doi.org/10.24433/CO.6352159.v1. Change the `save_result` argument to 1 to save denoised images.

**Comment by EB79** [comment]
> Hi, I am not sure about how you tested our model, but you can also check and use our model using the Code Ocean platform on https://doi.org/10.24433/CO.6352159.v1. Change the `save_result` argument to 1 to save denoised images.

Thank you for your response. I recreated your environment on the codeocean.com platform, executed the run file, and adjusted the parser arguments input as per your instructions. However, it appears that we are unable to save results such as images in the reproducible run. 

If possible, could you please provide some test results with lower noise percentages, such as 10% or 20%, to further investigate the capabilities of your model? (I was impressed by the 95% noise in your paper already!)

**Comment by AliRafiee7** [comment]
> > Hi, I am not sure about how you tested our model, but you can also check and use our model using the Code Ocean platform on https://doi.org/10.24433/CO.6352159.v1. Change the `save_result` argument to 1 to save denoised images.
> 
> Thank you for your response. I recreated your environment on the codeocean.com platform, executed the run file, and adjusted the parser arguments input as per your instructions. However, it appears that we are unable to save results such as images in the reproducible run.
> 
> If possible, could you please provide some test results with lower noise percentages, such as 10% or 20%, to further investigate the capabilities of your model? (I was impressed by the 95% noise in your paper already!)

You can simply run the codes for noise density of 10% and 20% by modifying values to your desired ones in the [run](https://codeocean.com/capsule/7353222/tree/v1/code/run) script.
For example, set the `save_result` argument to 1 in the line of 19 in the [run](https://codeocean.com/capsule/7353222/tree/v1/code/run) script for saving all denoised images, i.e.,
`python test.py --noise_density $noise_density --image_channels 1 --model_name model_050.hdf5 --test_dir ../data/Test --dataset $dataset --result_dir results --save_result 1`
